flags: {}
extra-package-dbs: []
packages:
- hpeg
- hpeg-bin
extra-deps:
- QuickCheck-2.9.2
- accelerate-1.0.0.0
- accelerate-llvm-ptx-1.0.0.1
- accelerate-io-1.0.0.0
- base-orphans-0.6
- bmp-1.2.6.3
- exceptions-0.8.3
- fclabels-2.0.3.2
- hashable-1.2.6.0
- hashtables-1.2.1.1
- mtl-2.2.1
- primitive-0.6.1.0
- random-1.1
- repa-3.4.1.2
- stm-2.4.4.1
- text-1.2.2.2
- tf-random-0.5
- transformers-compat-0.5.1.4
- unique-0
- unordered-containers-0.2.8.0
- vector-0.11.0.0
- accelerate-llvm-1.0.0.0
- cuda-0.7.5.3
- dlist-0.8.0.2
- llvm-hs-4.0.1.0
- llvm-hs-pure-4.0.0.0
- abstract-deque-0.3
- chaselev-deque-0.5.0.5
- data-default-class-0.1.2.0
- mwc-random-0.13.6.0
- parsec-3.1.11
- utf8-string-1.0.1.1
- atomic-primops-0.8.0.4
- math-functions-0.2.1.0
- vector-th-unbox-0.2.1.6
- lzma-0.0.0.3


resolver: ghc-8.0.2
